"""
Django settings for fixpoint_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_config(name, default=''):
    return [value.strip() for value in config(name, default=default).split(',') if value.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY', default=config('DJANGO_SECRET_KEY', default=''))
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = csv_config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,.vercel.app',
)
CSRF_TRUSTED_ORIGINS = csv_config('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'storages',        # for Supabase Storage (install: pip install django-storages boto3)
    'pages',
    'fixpoint_backend.users',
    'fixpoint_backend.issues',
    'fixpoint_backend.attachments',
    'fixpoint_backend.comments',
    'fixpoint_backend.delete_requests',
    'fixpoint_backend.notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fixpoint_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fixpoint_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}

CORS_ALLOWED_ORIGINS = csv_config('CORS_ALLOWED_ORIGINS')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = 'dashboard'  # Where to redirect after login
LOGOUT_REDIRECT_URL = '/'  # Where to redirect after logout


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

AUTH_USER_MODEL = 'users.CustomUser'

# Supabase Storage (S3-compatible) — set these in .env when ready
_SUPABASE_STORAGE_KEY = config('SUPABASE_STORAGE_KEY', default=None)
_SUPABASE_STORAGE_SECRET = config('SUPABASE_STORAGE_SECRET', default=None)
_SUPABASE_STORAGE_URL = config('SUPABASE_STORAGE_URL', default=None)
_SUPABASE_URL = config('SUPABASE_URL', default=None)
_SUPABASE_STORAGE_BUCKET = config('SUPABASE_STORAGE_BUCKET', default='attachments')
_SUPABASE_STORAGE_PUBLIC = config('SUPABASE_STORAGE_PUBLIC', default=False, cast=bool)

if _SUPABASE_STORAGE_KEY and _SUPABASE_STORAGE_SECRET and _SUPABASE_STORAGE_URL:
    _SUPABASE_STORAGE_URL = _SUPABASE_STORAGE_URL.rstrip('/')
    _SUPABASE_URL = _SUPABASE_URL.rstrip('/') if _SUPABASE_URL else None

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'BACKEND': "django.core.files.storage.FileSystemStorage",
        },
        'staticfiles': {
            'BACKEND': 'whiteoise.storage.CompressedManifestStaticFilesStorage',
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',

        },
    }
    AWS_ACCESS_KEY_ID = _SUPABASE_STORAGE_KEY
    AWS_SECRET_ACCESS_KEY = _SUPABASE_STORAGE_SECRET
    AWS_STORAGE_BUCKET_NAME = _SUPABASE_STORAGE_BUCKET
    AWS_S3_ENDPOINT_URL = _SUPABASE_STORAGE_URL
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = not _SUPABASE_STORAGE_PUBLIC

    if _SUPABASE_STORAGE_PUBLIC and _SUPABASE_URL:
        AWS_S3_CUSTOM_DOMAIN = (
            f"{_SUPABASE_URL.replace('https://', '').replace('http://', '')}"
            f"/storage/v1/object/public/{_SUPABASE_STORAGE_BUCKET}"
        )
        AWS_S3_URL_PROTOCOL = 'https:'
        MEDIA_URL = f"{_SUPABASE_URL}/storage/v1/object/public/{_SUPABASE_STORAGE_BUCKET}/"
    else:
        MEDIA_URL = f"{_SUPABASE_STORAGE_URL}/{_SUPABASE_STORAGE_BUCKET}/"
else:
    # Fallback to local media during development (before Supabase Storage is configured)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
