# Generated by Django 6.0.6 on 2026-07-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/')),
                ('fileName', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=50)),
                ('fileSize', models.PositiveIntegerField(help_text='File size in bytes')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
    ]
